############# English navigation ##############

# main menu
[[main]]
name = "首页"
pageRef = "/"
weight = 1

[[main]]
name = "关于我们"
pageRef = "/about"
weight = 2

[[main]]
name = "服务"
pageRef = "/services"
weight = 3

[[main]]
name = "解决方案"
pageRef = "/solution"
weight = 4


# footer menu
[[footer]]
name = "关于我们"
pageRef = "/about"
weight = 1

[[footer]]
name = "服务"
pageRef = "/services"
weight = 2

[[footer]]
name = "解决方案"
pageRef = "/solution"
weight = 3

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 4
